#!/usr/bin/env python3

# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate bootstrap registry fragments for loongsuite-distro.

This script generates one package-local registry fragment per instrumentation
package. The stable bootstrap_gen.py compatibility module imports those
fragments and exposes the libraries and default_instrumentations lists used by
loongsuite-bootstrap.

Package naming and version strategy:
- instrumentation-genai/* packages: renamed to loongsuite-* prefix
- instrumentation-loongsuite/* packages: keep loongsuite-* prefix
- instrumentation/* packages: keep opentelemetry-* prefix (from upstream PyPI)

Version strategy:
- --upstream-version: Version for upstream opentelemetry-instrumentation-* packages
- --loongsuite-version: Version for loongsuite-* packages

Usage:
  # Generate with default versions from source
  python scripts/loongsuite/generate_loongsuite_bootstrap.py

  # Generate with specific versions for release
  python scripts/loongsuite/generate_loongsuite_bootstrap.py \\
    --upstream-version 0.60b1 \\
    --loongsuite-version 0.1.0
"""

import argparse
import json
import logging
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

import tomli

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("loongsuite_bootstrap_generator")

scripts_path = Path(__file__).parent
root_path = scripts_path.parent.parent
SOURCE_GENAI_RENAMED = "genai-renamed"
SOURCE_UPSTREAM = "upstream"
SOURCE_LOONGSUITE = "loongsuite"

bootstrap_dir = (
    root_path / "loongsuite-distro" / "src" / "loongsuite" / "distro"
)
registry_path = bootstrap_dir / "bootstrap_registry"
gen_path = bootstrap_dir / "bootstrap_gen.py"

_bootstrap_gen_template = """{header}

\"\"\"Compatibility exports for the LoongSuite bootstrap registry.\"\"\"

from loongsuite.distro.bootstrap_registry import (
    default_instrumentations,
    libraries,
)

__all__ = [\"default_instrumentations\", \"libraries\"]
"""

_registry_init_template = """{header}

\"\"\"Package-scoped bootstrap registry fragments for LoongSuite distro.\"\"\"

from __future__ import annotations

from importlib import import_module
from pkgutil import iter_modules
from typing import Any


_SOURCE_SORT_ORDER = {
    "genai-renamed": 0,
    "upstream": 1,
    "loongsuite": 2,
}


def _iter_registry_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    package_path = globals()["__path__"]
    for module_info in sorted(
        iter_modules(package_path),
        key=lambda info: info.name,
    ):
        if module_info.ispkg or module_info.name.startswith(\"_\"):
            continue

        module = import_module(f\"{__name__}.{module_info.name}\")
        registry = getattr(module, \"REGISTRY\", None)
        if registry is not None:
            entries.append(registry)

    return sorted(
        entries,
        key=lambda registry: (
            _SOURCE_SORT_ORDER.get(registry.get("source"), 99),
            registry.get("package", ""),
        ),
    )


def load_bootstrap_registry() -> tuple[list[dict[str, str]], list[str]]:
    libraries: list[dict[str, str]] = []
    default_instrumentations: list[str] = []

    for registry in _iter_registry_entries():
        instrumentation = registry[\"instrumentation\"]
        target_libraries = registry.get(\"libraries\") or []
        if not target_libraries:
            default_instrumentations.append(instrumentation)
            continue

        for target_library in target_libraries:
            libraries.append(
                {
                    \"library\": target_library,
                    \"instrumentation\": instrumentation,
                }
            )

    return libraries, default_instrumentations


libraries, default_instrumentations = load_bootstrap_registry()

__all__ = [
    \"default_instrumentations\",
    \"libraries\",
    \"load_bootstrap_registry\",
]
"""

_registry_fragment_template = """{header}

# DO NOT EDIT. THIS FILE WAS AUTOGENERATED FROM INSTRUMENTATION PACKAGES.
# RUN `python scripts/loongsuite/generate_loongsuite_bootstrap.py` TO REGENERATE.
#
# Generated with options:
#   --upstream-version: {upstream_version}
#   --loongsuite-version: {loongsuite_version}

REGISTRY = {registry}
"""


def _registry_module_name(package_name: str) -> str:
    """Return a stable Python module name for a package registry fragment."""
    normalized = package_name.replace("-", "_").replace(".", "_").lower()
    return re.sub(r"[^a-z0-9_]", "_", normalized)


def _registry_entry(pkg: dict) -> dict:
    libraries = [
        *pkg.get("instruments", []),
        *pkg.get("instruments-any", []),
    ]
    return {
        "source": pkg.get("bootstrap-source", "unknown"),
        "package": pkg["name"],
        "instrumentation": pkg["requirement"],
        "libraries": libraries,
        "default": not libraries,
    }


def _render_python_string(value: str) -> str:
    return json.dumps(value)


def _render_registry_literal(entry: dict) -> str:
    lines = [
        "{",
        f'    "source": {_render_python_string(entry["source"])},',
        f'    "package": {_render_python_string(entry["package"])},',
        (
            '    "instrumentation": '
            f"{_render_python_string(entry['instrumentation'])},"
        ),
    ]

    if entry["libraries"]:
        lines.append('    "libraries": [')
        for library in entry["libraries"]:
            lines.append(f"        {_render_python_string(library)},")
        lines.append("    ],")
    else:
        lines.append('    "libraries": [],')

    lines.extend(
        [
            f'    "default": {entry["default"]},',
            "}",
        ]
    )
    return "\n".join(lines)


def _render_registry_module(
    entry: dict,
    header: str,
    upstream_version: Optional[str],
    loongsuite_version: Optional[str],
) -> str:
    registry = _render_registry_literal(entry)
    return _registry_fragment_template.format(
        header=header,
        registry=registry,
        upstream_version=upstream_version or "(from source)",
        loongsuite_version=loongsuite_version or "(from source)",
    )


def _write_registry_init(header: str) -> None:
    registry_path.mkdir(parents=True, exist_ok=True)
    with open(registry_path / "__init__.py", "w", encoding="utf-8") as f:
        f.write(_registry_init_template.replace("{header}", header))


def _write_bootstrap_gen(header: str) -> None:
    gen_path.parent.mkdir(parents=True, exist_ok=True)
    with open(gen_path, "w", encoding="utf-8") as f:
        f.write(_bootstrap_gen_template.format(header=header))


def _remove_stale_registry_fragments() -> None:
    if not registry_path.exists():
        return

    for path in registry_path.glob("*.py"):
        if path.name == "__init__.py" or path.name.startswith("_"):
            continue
        path.unlink()


def _load_upstream_bootstrap_context():
    # Import the upstream bootstrap helper only when full package scanning runs.
    # Unit tests for the local registry rendering helpers should not need the
    # upstream generator's formatting dependencies.
    scripts_parent = str(Path(__file__).resolve().parent.parent)
    if scripts_parent not in sys.path:
        sys.path.insert(0, scripts_parent)

    from generate_instrumentation_bootstrap import (  # noqa: PLC0415
        independent_packages,
        packages_to_exclude,
    )
    from otel_packaging import (  # noqa: PLC0415
        get_instrumentation_packages as get_upstream_packages,
    )

    return independent_packages, packages_to_exclude, get_upstream_packages


def get_genai_packages_to_rename(
    excluded_packages: Optional[set[str]] = None,
) -> dict[str, str]:
    """
    Dynamically discover instrumentation-genai packages that need renaming.

    Rule: All packages under instrumentation-genai/ with opentelemetry-* prefix
    should be renamed to loongsuite-* prefix, except those in packages_to_exclude.

    Returns:
        Dict mapping original name to new name, e.g.:
        {"opentelemetry-instrumentation-vertexai": "loongsuite-instrumentation-vertexai"}
    """
    excluded_packages = excluded_packages or set()
    result = {}
    genai_dir = root_path / "instrumentation-genai"

    if not genai_dir.exists():
        return result

    for pkg_dir in genai_dir.iterdir():
        if not pkg_dir.is_dir():
            continue

        pkg_name = pkg_dir.name

        # Rule: opentelemetry-* prefix packages should be renamed to loongsuite-*
        if pkg_name.startswith("opentelemetry-"):
            # Skip packages in upstream exclude list
            if pkg_name in excluded_packages:
                continue

            new_name = pkg_name.replace("opentelemetry-", "loongsuite-")
            result[pkg_name] = new_name

    return result


def get_instrumentation_packages(
    upstream_version: Optional[str] = None,
    loongsuite_version: Optional[str] = None,
):
    """
    Get all instrumentation packages from various directories.

    Args:
        upstream_version: Override version for upstream opentelemetry-* packages
        loongsuite_version: Override version for loongsuite-* packages

    Note:
        When the same package name exists in both instrumentation-genai and
        instrumentation-loongsuite, the version from instrumentation-loongsuite
        takes precedence (overwrites the earlier one).
    """
    packages = []
    seen_packages: dict[str, int] = {}  # name -> index in packages list

    logger.info("Scanning instrumentation packages...")
    (
        independent_packages,
        packages_to_exclude,
        get_upstream_packages,
    ) = _load_upstream_bootstrap_context()
    excluded_packages = set(packages_to_exclude)

    # Dynamically get packages that need renaming
    genai_packages_to_rename = get_genai_packages_to_rename(excluded_packages)

    # Get packages from upstream directories (instrumentation, instrumentation-genai)
    logger.info(
        "Processing upstream packages (instrumentation, instrumentation-genai)..."
    )
    for pkg in get_upstream_packages(
        independent_packages=independent_packages
    ):
        pkg_name = pkg["name"]

        # Skip packages in exclude list (follow upstream behavior)
        if pkg_name in excluded_packages:
            continue

        # Check if this package should be renamed (instrumentation-genai with opentelemetry-* prefix)
        if pkg_name in genai_packages_to_rename:
            new_name = genai_packages_to_rename[pkg_name]
            logger.info(f"Renaming {pkg_name} -> {new_name}")
            pkg["name"] = new_name
            pkg["bootstrap-source"] = SOURCE_GENAI_RENAMED

            # Use loongsuite version for renamed packages
            if loongsuite_version:
                pkg["requirement"] = f"{new_name}=={loongsuite_version}"
            else:
                # Keep original version but update name
                pkg["requirement"] = pkg["requirement"].replace(
                    pkg_name, new_name
                )
        else:
            pkg["bootstrap-source"] = SOURCE_UPSTREAM

            # Use upstream version for opentelemetry-* packages
            if upstream_version and pkg_name.startswith("opentelemetry-"):
                pkg["requirement"] = f"{pkg_name}=={upstream_version}"

        # Track package by name (for deduplication)
        final_name = pkg["name"]
        if final_name in seen_packages:
            # Replace existing package (instrumentation-loongsuite should win)
            idx = seen_packages[final_name]
            packages[idx] = pkg
        else:
            seen_packages[final_name] = len(packages)
            packages.append(pkg)

    # Scan instrumentation-loongsuite directory
    loongsuite_dir = root_path / "instrumentation-loongsuite"
    if loongsuite_dir.exists():
        logger.info(
            "Processing loongsuite packages (instrumentation-loongsuite)..."
        )
        pkg_dirs = sorted([d for d in loongsuite_dir.iterdir() if d.is_dir()])
        for pkg_dir in pkg_dirs:
            pyproject_toml = pkg_dir / "pyproject.toml"
            if not pyproject_toml.exists():
                continue

            try:
                # Get version using hatch command
                version = subprocess.check_output(
                    "hatch version",
                    shell=True,
                    cwd=pkg_dir,
                    universal_newlines=True,
                    stderr=subprocess.DEVNULL,
                ).strip()

                # Read pyproject.toml
                with open(pyproject_toml, "rb") as f:
                    pyproject = tomli.load(f)

                pkg_name = pyproject["project"]["name"]

                if pkg_name in excluded_packages:
                    continue

                # Get optional dependencies
                optional_deps = pyproject["project"].get(
                    "optional-dependencies", {}
                )
                instruments = optional_deps.get("instruments", [])
                instruments_any = optional_deps.get("instruments-any", [])

                # Use loongsuite version if specified
                if loongsuite_version:
                    requirement = f"{pkg_name}=={loongsuite_version}"
                elif pkg_name in independent_packages:
                    specifier = independent_packages[pkg_name]
                    requirement = (
                        f"{pkg_name}{specifier}"
                        if specifier
                        else f"{pkg_name}=={version}"
                    )
                else:
                    requirement = f"{pkg_name}=={version}"

                new_pkg = {
                    "bootstrap-source": SOURCE_LOONGSUITE,
                    "name": pkg_name,
                    "version": version,
                    "instruments": instruments,
                    "instruments-any": instruments_any,
                    "requirement": requirement,
                }

                # Deduplication: instrumentation-loongsuite takes precedence
                if pkg_name in seen_packages:
                    idx = seen_packages[pkg_name]
                    logger.info(
                        f"Overwriting {pkg_name} with instrumentation-loongsuite version"
                    )
                    packages[idx] = new_pkg
                else:
                    seen_packages[pkg_name] = len(packages)
                    packages.append(new_pkg)
            except subprocess.CalledProcessError as e:
                logger.warning(
                    f"Could not get hatch version from {pkg_dir.name}: {e}"
                )
                continue
            except Exception as e:
                logger.warning(f"Failed to process {pkg_dir.name}: {e}")
                continue

    return packages


def main():
    parser = argparse.ArgumentParser(
        description="Generate bootstrap registry fragments for loongsuite-distro"
    )
    parser.add_argument(
        "--upstream-version",
        type=str,
        default=None,
        help="Override version for upstream opentelemetry-instrumentation-* packages (e.g., 0.60b1)",
    )
    parser.add_argument(
        "--loongsuite-version",
        type=str,
        default=None,
        help="Override version for loongsuite-* packages (e.g., 0.1.0)",
    )
    args = parser.parse_args()

    # Read license header
    header_path = scripts_path.parent / "license_header.txt"
    if header_path.exists():
        with open(header_path, "r", encoding="utf-8") as f:
            header = f.read()
    else:
        header = "# Copyright The OpenTelemetry Authors\n# Licensed under the Apache License, Version 2.0\n"

    # Get all packages
    packages = get_instrumentation_packages(
        upstream_version=args.upstream_version,
        loongsuite_version=args.loongsuite_version,
    )
    logger.info(f"Found {len(packages)} instrumentation packages")

    entries = [_registry_entry(pkg) for pkg in packages]
    default_instrumentations = [entry for entry in entries if entry["default"]]
    library_mappings = sum(len(entry["libraries"]) for entry in entries)

    logger.info("Generating bootstrap registry fragments...")
    _write_registry_init(header)
    _write_bootstrap_gen(header)
    _remove_stale_registry_fragments()

    written_paths: set[Path] = set()
    for entry in entries:
        registry_file = (
            registry_path / f"{_registry_module_name(entry['package'])}.py"
        )
        if registry_file in written_paths:
            raise RuntimeError(
                f"duplicate bootstrap registry fragment: {registry_file}"
            )
        written_paths.add(registry_file)

        with open(registry_file, "w", encoding="utf-8") as f:
            f.write(
                _render_registry_module(
                    entry,
                    header,
                    args.upstream_version,
                    args.loongsuite_version,
                )
            )

    logger.info(
        "generated %d registry fragments in %s", len(entries), registry_path
    )
    logger.info("generated %s", gen_path)
    logger.info(
        "  - %d default instrumentations", len(default_instrumentations)
    )
    logger.info("  - %d library mappings", library_mappings)


if __name__ == "__main__":
    main()
