# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Extended semantic convention attributes for GenAI operations.
These attributes are not yet available in the standard opentelemetry-semantic-conventions package.
"""

from enum import Enum
from typing import Final

# Common attributes
GEN_AI_TOOL_DEFINITIONS: Final = "gen_ai.tool.definitions"
"""
The tool definitions used by the model.
"""

# Embedding attributes
GEN_AI_EMBEDDINGS_DIMENSION_COUNT: Final = "gen_ai.embeddings.dimension.count"
"""
The dimensionality of the embedding vectors generated by the model.
"""

# Tool call attributes
GEN_AI_TOOL_CALL_ARGUMENTS: Final = "gen_ai.tool.call.arguments"
"""
The arguments or parameters passed to the tool during invocation.
"""

GEN_AI_TOOL_CALL_RESULT: Final = "gen_ai.tool.call.result"
"""
The result returned by the tool after execution.
"""

# Retrieve attributes
GEN_AI_RETRIEVAL_QUERY: Final = "gen_ai.retrieval.query"
"""
The query string used to retrieve documents from a vector database or search system.
"""

GEN_AI_RETRIEVAL_DOCUMENTS: Final = "gen_ai.retrieval.documents"
"""
The documents retrieved from the search or vector database.
"""

# Rerank attributes
GEN_AI_RERANK_DOCUMENTS_COUNT: Final = "gen_ai.rerank.documents.count"
"""
The number of documents provided as input to the reranking operation.
"""

GEN_AI_RERANK_SCORING_PROMPT: Final = "gen_ai.rerank.scoring_prompt"
"""
Custom scoring prompt used by LLM-based rerankers to evaluate document relevance.
"""

GEN_AI_RERANK_RETURN_DOCUMENTS: Final = "gen_ai.rerank.return_documents"
"""
Whether the reranker should return the full document content in the response.
"""

GEN_AI_RERANK_MAX_CHUNKS_PER_DOC: Final = "gen_ai.rerank.max_chunks_per_doc"
"""
Maximum number of chunks to consider per document during reranking.
"""

GEN_AI_RERANK_DEVICE: Final = "gen_ai.rerank.device"
"""
The computation device used for inference in model-based rerankers.
"""

GEN_AI_RERANK_BATCH_SIZE: Final = "gen_ai.rerank.batch_size"
"""
The batch size used for processing documents during reranking.
"""

GEN_AI_RERANK_MAX_LENGTH: Final = "gen_ai.rerank.max_length"
"""
Maximum sequence length for tokenization in the reranking model.
"""

GEN_AI_RERANK_NORMALIZE: Final = "gen_ai.rerank.normalize"
"""
Whether to normalize the relevance scores returned by the reranker.
"""

GEN_AI_RERANK_INPUT_DOCUMENTS: Final = "gen_ai.rerank.input_documents"
"""
The documents provided as input to the reranking operation.
"""

GEN_AI_RERANK_OUTPUT_DOCUMENTS: Final = "gen_ai.rerank.output_documents"
"""
The reranked documents returned by the reranking operation.
"""


class GenAiExtendedOperationNameValues(Enum):
    RETRIEVE_DOCUMENTS = "retrieve_documents"
    """Retrieve documents operation."""

    RERANK_DOCUMENTS = "rerank_documents"
    """Rerank documents operation."""


class GenAiExtendedProviderNameValues(Enum):
    DASHSCOPE = "dashscope"
    """DashScope."""

    OLLAMA = "ollama"
    """Ollama."""

    MOONSHOT = "moonshot"
    """Moonshot."""


# LoongSuite Extension: GenAI operation kind attribute
GEN_AI_SPAN_KIND: Final = "gen_ai.span.kind"
"""
The semantic type of GenAI operation (e.g., LLM, AGENT, EMBEDDING).
This attribute extends OpenTelemetry semantics to classify GenAI-specific operations
for scenarios like Completion, Chat, RAG, Agent, and Tool execution.

Note: This is an Attribute, distinct from OpenTelemetry's Span kind field.
"""


class GenAiSpanKindValues(Enum):
    AGENT = "AGENT"
    """Agent operation (create_agent, invoke_agent)."""

    LLM = "LLM"
    """Large Language Model operation (chat completion)."""

    EMBEDDING = "EMBEDDING"
    """Embedding generation operation."""

    TOOL = "TOOL"
    """Tool execution operation."""

    RETRIEVER = "RETRIEVER"
    """Document retrieval operation."""

    RERANKER = "RERANKER"
    """Document reranking operation."""
