# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DO NOT EDIT. THIS FILE WAS AUTOGENERATED FROM INSTRUMENTATION PACKAGES.
# RUN `python scripts/loongsuite/generate_loongsuite_bootstrap.py` TO REGENERATE.
#
# Generated with options:
#   --upstream-version: (from source)
#   --loongsuite-version: (from source)

REGISTRY = {
    "source": "upstream",
    "package": "opentelemetry-instrumentation-pymemcache",
    "instrumentation": "opentelemetry-instrumentation-pymemcache==0.62b0.dev",
    "libraries": [
        "pymemcache >= 1.3.5, < 5",
    ],
    "default": False,
}
